spec:
  inputs:
    topic:
      description: "Kafka topic to create"
      type: string
    group:
      description: "Kafka group to create"
      type: string

---

stages:
  - kafka

kafka_create_topic:
  stage: kafka
  image: docker:28.4.0-cli
  variables:
    DOCKER_HOST: tcp://docker-shared:2375
    TOPIC: $[[ inputs.topic ]]
  script:
    - .ci/scripts/kafka/create_topic.sh
  rules:
    - if: '"$[[ inputs.topic ]]" != ""'
    - when: never

kafka_init_consumer:
  stage: kafka
  image: docker:28.4.0-cli
  variables:
    DOCKER_HOST: tcp://docker-shared:2375
    TOPIC: $[[ inputs.topic ]]
    GROUP: $[[ inputs.group ]]
  script:
    - .ci/scripts/kafka/init_consumer.sh
  needs:
    - kafka_create_topic
  rules:
    - if: '"$[[ inputs.topic ]]" != "" && "$[[ inputs.group ]]" != ""'
    - when: never
