spec:
  inputs:
    pull:
      description: "Pull Ollama model"
      type: string

---

stages:
  - ollama

ollama_pull:
  stage: ollama
  image: docker:28.4.0-cli
  variables:
    DOCKER_HOST: tcp://docker-shared:2375
    PULL: $[[ inputs.pull ]]
  script:
    - .ci/scripts/ollama/pull.sh
  rules:
    - if: '"$[[ inputs.pull ]]" != ""'
    - when: never
