stages:
  - deploy

deploy:
  stage: deploy
  image: docker:28.4.0-cli
  variables:
    DOCKER_HOST: tcp://docker-shared:2375
  script:
    - docker compose -p datalab -f infra/services/docker/compose.yml up -d
    - sleep 10 && docker ps
  rules:
    - changes:
        - infra/services/docker/**
