services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_ACCESS_KEY}
    volumes:
      - minio:/data
    networks:
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      retries: 5
    restart: unless-stopped
    command: server /data --console-address ":9001"

  minio-mc:
    image: minio/mc:RELEASE.2025-04-16T18-13-26Z
    networks:
      - minio
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 $S3_ACCESS_KEY_ID $S3_SECRET_ACCESS_KEY;
      /usr/bin/mc mb --ignore-existing minio/${S3_BUCKET};
      "
    restart: no

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    healthcheck:
      test: ["CMD", "ollama", "ls"]
      interval: 10s
      retries: 3
    restart: unless-stopped

  ollama-models:
    image: alpine/curl:latest
    networks:
      - ollama
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      MODELS: ${OLLAMA_MODELS}
    entrypoint: |
      /bin/sh -c '
      IFS=,; set -- $${MODELS};
      for model in "$$@"; do
        echo "==> Downloading model: $$model"
        curl -X POST http://ollama:11434/api/pull \
          -H "Content-Type: application/json" \
          -d "{\"name\": \"$$model\"}"
      done
      '
    restart: no

  mlflow:
    build:
      context: ./docker/mlflow
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - mlflow:/mlflow
    networks:
      - mlflow
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://${S3_ENDPOINT}
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${S3_REGION}
      AWS_S3_ADDRESSING_STYLE: ${S3_URL_STYLE}
    command: >
      mlflow server
        --backend-store-uri sqlite:///mlflow/mlflow.db
        --serve-artifacts
        --artifacts-destination s3://${S3_MLFLOW_BUCKET}/${S3_MLFLOW_ARTIFACTS_PREFIX}
        --host 0.0.0.0
        --port 5000
    healthcheck:
      test: >
        python -c "import urllib.request;
        urllib.request.urlopen('http://localhost:5000')"
      interval: 10s
      retries: 5
    restart: unless-stopped

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: INTERNAL://:29092,CONTROLLER://:9093,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,CONTROLLER://kafka:9093,EXTERNAL://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka:/var/lib/kafka/data
    networks:
      - kafka
    healthcheck:
      test: [
        "CMD",
        "bash", "-c",
        "/opt/kafka/bin/kafka-metadata-quorum.sh
          --bootstrap-server kafka:29092
          describe
          --status
        | grep -q -w LeaderId"
      ]
      interval: 15s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  minio:
  ollama:
  mlflow:
  kafka:

networks:
  ollama:
  minio:
  mlflow:
  kafka:
