[project]
name = "datalab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "dbt-core>=1.9.6",
    "dbt-duckdb>=1.9.3",
    "minio>=7.2.15",
]
