
version: 2

models:
  - name: dsn_nodes_users
    description: Deezer user nodes
    columns:
      - name: node_id
        description: Unique numerical node ID from a shared sequence
        data_tests:
          - not_null
          - unique
      - name: user_id
        description: Deezer user ID
        data_tests:
          - not_null
      - name: source
        description: Data source for the node (always Deezer)
        data_tests:
          - dbt_utils.expression_is_true:
              expression: "= 'Deezer'"
      - name: country
        description: Deezer user country
        data_tests:
          - dbt_utils.expression_is_true:
              expression: "IN ('HR', 'HU', 'RO')"

  - name: msdsl_nodes_tracks
    description: Million Song Dataset, Spotify, and Last.fm music tracks
    columns:
      - name: node_id
        description: Unique numerical node ID from a shared sequence
        data_tests:
          - not_null
          - unique
      - name: track_id
        description: String track identifier starting with TR
        data_tests:
          - not_null
          - unique
      - name: name
        description: Track title
        data_tests:
          - not_null
      - name: artist
        description: Track artist
        data_tests:
          - not_null
      - name: year
        description: Track release year
        data_tests:
          - not_null

  - name: msdsl_nodes_users
    description: Million Song Dataset, Spotify, and Last.fm users
    columns:
      - name: node_id
        description: Unique numerical node ID from a shared sequence
        data_tests:
          - not_null
          - unique
      - name: user_id
        description: User ID for Million Song Dataset, Spotify, and Last.fm (MSDSL)
        data_tests:
          - not_null
      - name: source
        description: Data source for the node (always MSDSL)
        data_tests:
          - dbt_utils.expression_is_true:
              expression: "= 'MSDSL'"

  - name: nodes_genres
    description: Deezer genres and MSDSL tags as genre nodes
    columns:
      - name: node_id
        description: Unique numerical node ID from a shared sequence
        data_tests:
          - not_null
          - unique
      - name: genre
        description: >
          All unique genres from DSN Croatian (HR), Hungarian (HU) and Romanian (RO),
          and all MSDSL tags as genres.
        data_tests:
          - not_null
          - unique
