
version: 2

models:
  - name: dsn_hr_genres
    description: Croatia genres per user
    columns:
      - name: user_id
        description: User ID, also the graph node ID suffix
        data_tests:
          - not_null
      - name: genres
        description: List of genres, formatted using title case
        data_tests:
          - not_null
          - list_not_empty

  - name: dsn_hu_genres
    description: Hungarian genres per user
    columns:
      - name: user_id
        description: User ID, also the graph node ID suffix
        data_tests:
          - not_null
      - name: genres
        description: List of genres, formatted using title case
        data_tests:
          - not_null
          - list_not_empty

  - name: dsn_ro_genres
    description: Romanian genres per user
    columns:
      - name: user_id
        description: User ID, also the graph node ID suffix
        data_tests:
          - not_null
      - name: genres
        description: List of genres, formatted using title case
        data_tests:
          - not_null
          - list_not_empty

  - name: dsn_hr_edges
    description: Croatian users with friendship relations on Deezer
    columns:
      - name: source_id
        description: Source user node ID
        data_tests:
          - not_null
      - name: target_id
        description: Target user node ID
        data_tests:
          - not_null

  - name: dsn_hu_edges
    description: Hungarian users with friendship relations on Deezer
    columns:
      - name: source_id
        description: Source user node ID
        data_tests:
          - not_null
      - name: target_id
        description: Target user node ID
        data_tests:
          - not_null

  - name: dsn_ro_edges
    description: Romanian users with friendship relations on Deezer
    columns:
      - name: source_id
        description: Source user node ID
        data_tests:
          - not_null
      - name: target_id
        description: Target user node ID
        data_tests:
          - not_null
