spec:
  inputs:
    topic:
      description: "Kafka topic to create"
      type: string
    group:
      description: "Kafka group to create"
      type: string

---

stages:
  - kafka

kafka_create_topic:
  stage: kafka
  image: docker:28.4.0-cli
  variables:
    DOCKER_HOST: tcp://docker-shared:2375
    TOPIC: $[[ inputs.topic ]]
  script:
    - 'echo "Creating topic if not exists: $TOPIC"'
    - |
      docker exec datalab-kafka-1 /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server localhost:29092 \
          --create --if-not-exists --topic "$TOPIC" \
          --partitions 1 \
          --replication-factor 1
  rules:
    - if: '"$[[ inputs.topic ]]" != ""'
    - when: never

kafka_init_consumer:
  stage: kafka
  image: docker:28.4.0-cli
  variables:
    DOCKER_HOST: tcp://docker-shared:2375
    TOPIC: $[[ inputs.topic ]]
    GROUP: $[[ inputs.group ]]
  script:
    - 'echo "Initializing consumer: topic $TOPIC, group $GROUP"'
    - |
      docker exec datalab-kafka-1 /opt/kafka/bin/kafka-console-consumer.sh \
          --bootstrap-server localhost:29092 \
          --topic "$TOPIC" \
          --group "$GROUP" \
          --timeout-ms 5000
  needs:
    - kafka_create_topic
  rules:
    - if: '"$[[ inputs.topic ]]" != "" && "$[[ inputs.group ]]" != ""'
    - when: never
