transform:
  outputs:
    lakehouse:
      type: duckdb
      path: "{{ env_var('LOCAL_DIR') }}/{{ env_var('ENGINE_DB') }}"
      extensions:
        - httpfs
        - parquet
        - ducklake
        - sqlite
      secrets:
        - type: s3
          region: "{{ env_var('S3_REGION') }}"
          key_id: "{{ env_var('S3_ACCESS_KEY') }}"
          secret: "{{ env_var('S3_SECRET_KEY') }}"
          endpoint: "{{ env_var('S3_ENDPOINT') }}"
          use_ssl: "{{ env_var('S3_USE_SSL') }}"
          url_style: "{{ env_var('S3_URL_STYLE') }}"
      attach:
        - path: ducklake:sqlite:{{ env_var('LOCAL_DIR') }}/{{ env_var('STAGE_DB') }}
          alias: lakehouse
          options:
            data_path: s3://{{ env_var('S3_BUCKET') }}/{{ env_var('S3_STAGE_PREFIX') }}
  target: lakehouse
