transform:
  outputs:
    lakehouse:
      type: duckdb
      path: "{{ env_var('LOCAL_DIR') }}/{{ env_var('ENGINE_DB') }}"
      extensions:
        - httpfs
        - parquet
        - ducklake
        - sqlite
      secrets:
        - type: s3
          region: "{{ env_var('S3_REGION') }}"
          key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
          secret: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"
          endpoint: "{{ env_var('S3_ENDPOINT') }}"
          use_ssl: "{{ env_var('S3_USE_SSL') }}"
          url_style: "{{ env_var('S3_URL_STYLE') }}"
      attach:
        - path: ducklake:sqlite:{{ env_var('LOCAL_DIR') }}/{{ env_var('STAGE_DB') }}
          alias: stage
          options:
            data_path: s3://{{ env_var('S3_BUCKET') }}/{{ env_var('S3_STAGE_PREFIX') }}
        - path: >
            ducklake:sqlite:{{ env_var('LOCAL_DIR') }}/{{ env_var('GRAPHS_MART_DB') }}
          alias: graphs
          options:
            data_path: >
              s3://{{ env_var('S3_BUCKET') }}/{{ env_var('S3_GRAPHS_MART_PREFIX') }}
        - path: >
            ducklake:sqlite:{{ env_var('LOCAL_DIR') }}/{{ env_var('ANALYTICS_MART_DB') }}
          alias: analytics
          options:
            data_path: >
              s3://{{ env_var('S3_BUCKET') }}/{{ env_var('S3_ANALYTICS_MART_PREFIX') }}
  target: lakehouse
