version: 2

models:
  - name: taoec_hs92_ccp_trade_2020_2023
    description: Country Trade by Partner and Product (HS92), aggregated for 2020-2023.
    columns:
      - name: country_id
        description: >-
          Numerical country ID (internal to Growth Labs) for the reporting country.
          This matches the IDs in the countries classification table.
        data_tests:
          - not_null
      - name: country_iso3_code
        description: >-
          Three digit country code (e.g., USA, PRT) for the reporting country.
        data_tests:
          - not_null
      - name: partner_country_id
        description: >-
          Numerical country ID (internal to Growth Labs) for the partner country.
          This matches the IDs in the countries classification table.
        data_tests:
          - not_null
      - name: partner_iso3_code
        description: >-
          Three digit country code (e.g., USA, PRT) for the partner country.
        data_tests:
          - not_null
      - name: product_id
        description: Numerical product ID (internal to Growth Labs).
        data_tests:
          - not_null
      - name: product_hs92_code
        description: >-
          HS92 6-digit product code. HS stands for Harmonized System, and it's a
          classification system used in international trade to categorize goods.
        data_tests:
          - not_null
      - name: export_value
        description: Export value in dollars (USD).
        data_tests:
          - not_null
      - name: import_value
        description: Import value in dollars (USD).
        data_tests:
          - not_null
